restaurante/restaurante/casa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    
    path('reserva/',views.reserva,name='reserva'),
    path('registrar/',views.registrar,name='registrar'),
    path('adicionar_prato/',views.adicionar_prato,name='adicionar_prato'),
    path('sair/',views.sair,name='sair'),
    path('ham/',views.ham,name='ham'),
    path('fritas/',views.fritas,name='fritas'),
    path('coca/',views.coca,name='coca'),
    # path('ir/',views.ir,name='ir'),
    path('retirar/<str:pratos>',views.retirar,name='retirar'),
    path('voltar/',views.voltar,name='voltar'),
    path('menu/',views.menu,name='menu'),
    path('retirar_prato/<str:prato>',views.retirar_prato,name='retirar_prato'),
    path('prato_pedido/<str:prato>',views.prato_pedido,name='prato_pedido'),
    path('deletar/',views.deletar,name='deletar')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurante/restaurante/restaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('casa/',include('casa.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurante/restaurante/casa/models.py
from django.db import models
from datetime import datetime

class Reservas(models.Model):
    horario_choices=(
        ('TR','Tarde'),
        ('MN','Manhã'),
        ('NO','Noite')
    )
    local_choices=(
        ('CN','Centro'),
        ('PR','Periferia')
    )
    nome=models.CharField(max_length=50)
    horarios=models.CharField(max_length=2 ,choices=horario_choices)
    locais=models.CharField(max_length=2 ,choices=local_choices)
    data_reserva = models.IntegerField(default=1)
    
    
    def __str__(self):
        return self.nome
    
class Carrinho(models.Model):
    usuario=models.CharField(max_length=50)
    identidade=models.IntegerField(default=1)
    atual=models.CharField(max_length=50,default='nulo')

    def __str__(self):
        return self.usuario

restaurante/restaurante/casa/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Reservas,Carrinho
from pathlib import Path
import pickle
import os
import os.path
def reserva(request):
    
    
    nome= request.POST.get('nome')
    horario= request.POST.get('horario')
    local= request.POST.get('local')
    dia= request.POST.get('dia')
    dias=int(dia)
    if 'reservar' in request.POST:
        if  Reservas.objects.filter(nome=nome).exists():
            return render (request, 'home.html',{'mensagem':'Já há reserva para esse cliente'})

        if dias>31 or dias<1:
            return render (request, 'home.html',{'mensagem':'Dia do mês inválido'})
        
        if Reservas.objects.filter(horarios=horario).filter(locais=local).filter(data_reserva=dia).exists():
            return render (request, 'home.html',{'mensagem':'reserva indisponível'})
        
        reservas=Reservas(
            nome=nome,
            horarios=horario,
            locais=local,
            data_reserva=dia

        )

        reservas.save()
        
        

        return render (request, 'home.html',{'reservas': reservas})

    elif  'cancelar' in request.POST:
        if  Reservas.objects.filter(horarios=horario).filter(locais=local).filter(data_reserva=dia).filter(nome=nome).exists():
            Reservas.objects.filter(horarios=horario).filter(locais=local).filter(data_reserva=dia).filter(nome=nome).delete()
            return render (request, 'home.html',{'mensagem':'reserva cancelada'})
        else:
            return render (request, 'home.html',{'mensagem':'reserva inexistente'})
    
    
def registrar(request):
    Carrinho.objects.filter(atual='atual').update(atual='nulo')
    usuario= request.POST.get('usuario')
    identidade=1
    if not Carrinho.objects.filter(usuario=usuario).exists():
        carrinho=Carrinho(
            usuario=usuario,
            identidade=identidade,
            atual='atual'
        )
        carrinho.save()
        carr={}
        pedido = Path(f'{usuario}.pkl')
        pedido.touch(exist_ok=True)
        with open(f'{usuario}.pkl', 'wb') as fp:# o novo dicionário é salvo no arquivo do carrinho.
                pickle.dump(carr, fp)

    
    else:
         Carrinho.objects.filter(usuario=usuario).update(atual='atual')
         if not os.path.isfile(f'{usuario}.pkl'):
              pedido = Path(f'{usuario}.pkl')
              pedido.touch(exist_ok=True)
              carr={}
              with open(f'{usuario}.pkl', 'wb') as fp:# o novo dicionário é salvo no arquivo do carrinho.
                pickle.dump(carr, fp)
    carro=Carrinho.objects.get(atual='atual')
    with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
    with open('preco.pkl', 'rb') as fp: 
            precos = pickle.load(fp)
     
    total=0
    lista=[]
    for pratos in carros.keys():
             if pratos in precos.keys():
                lista.append(pratos)
                price=int(precos[pratos])
                total+=carros[pratos]*price
    
    return render (request, 'home.html',{'mensagem3': f'{usuario}','mensagem': f'Você entrou com o pedido {usuario}','preco':total,'lista':lista,'carro':carros})
def adicionar_prato(request):
    
    pedido = Path('preco.pkl')
    pedido.touch(exist_ok=True)
    
    prato= request.POST.get('nome_prato')
    precos= request.POST.get('preco_prato')
    
    with open('preco.pkl', 'rb') as fp:
            preco = pickle.load(fp)
    if prato in preco.keys():
            return render (request,'home.html',{'prato':'prato já existente'})
    else:
        preco[prato]=precos
            
        with open('preco.pkl', 'wb') as fp:
            pickle.dump(preco, fp)
        return render (request,'home.html',{'prato': 'prato adicionado'})
    
def sair(request):
     
     Carrinho.objects.filter(atual='atual').update(atual='nulo')
     return render(request, 'home.html',{'mensagem':'saída do pedido atual'})

def ham(request):
     if not Carrinho.objects.filter(atual='atual').exists():
          return render (request,'home.html',{'mensagem3': f'{carro}','mensagem2':'É necessário estar logado em um pedido para adicionar pratos'})
     else:
        
        carro=Carrinho.objects.get(atual='atual')
        with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
        if 'hamburguer' in carros.keys(): 
                carros['hamburguer']+=1
                with open(f'{carro}.pkl', 'wb') as fp:
                    pickle.dump(carros, fp)
        else:
            carros['hamburguer']=1
            with open(f'{carro}.pkl', 'wb') as fp:
                pickle.dump(carros, fp)

        if not Carrinho.objects.filter(atual='atual').exists():
          return render (request,'home.html',{'mensagem':'É necessário estar logado em um pedido para gerenciar o pedido'})
     
        carro=Carrinho.objects.get(atual='atual')
        with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
        with open('preco.pkl', 'rb') as fp: 
            precos = pickle.load(fp)
     
        total=0
        lista=[]
        for pratos in carros.keys():
             if pratos in precos.keys():
                lista.append(pratos)
                price=int(precos[pratos])
                total+=carros[pratos]*price

                
                
        return render (request,'home.html',{'mensagem3': f'{carro}','mensagem2': 'hamurguer adicionado ao pedido','preco':total,'lista':lista,'carro':carros})
     
    
def fritas(request):
     if not Carrinho.objects.filter(atual='atual').exists():
          return render (request,'home.html',{'mensagem2':'É necessário estar logado em um pedido para adicionar pratos'})
     else:
        carro=Carrinho.objects.get(atual='atual')

        with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
        if 'fritas' in carros.keys(): 
                carros['fritas']+=1
                with open(f'{carro}.pkl', 'wb') as fp:
                    pickle.dump(carros, fp)
        else:
            carros['fritas']=1
            with open(f'{carro}.pkl', 'wb') as fp:
                pickle.dump(carros, fp)

        if not Carrinho.objects.filter(atual='atual').exists():
          return render (request,'home.html',{'mensagem':'É necessário estar logado em um pedido para gerenciar o pedido'})
     
     carro=Carrinho.objects.get(atual='atual')
     with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
     with open('preco.pkl', 'rb') as fp: 
            precos = pickle.load(fp)
     
     total=0
     lista=[]
     for pratos in carros.keys():
             if pratos in precos.keys():
                lista.append(pratos)
                price=int(precos[pratos])
                total+=carros[pratos]*price
        
     return render (request,'home.html',{'mensagem3': f'{carro}', 'mensagem2': 'fritas adicionado ao pedido','preco':total,'lista':lista,'carro':carros})
     
def coca(request):
     if not Carrinho.objects.filter(atual='atual').exists():
          return render (request,'home.html',{'mensagem2':'É necessário estar logado em um pedido para adicionar pratos'})
     else:
        carro=Carrinho.objects.get(atual='atual')
        

        with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
        if 'coca' in carros.keys(): 
                carros['coca']+=1
                with open(f'{carro}.pkl', 'wb') as fp:
                    pickle.dump(carros, fp)
        else:
            carros['coca']=1
            with open(f'{carro}.pkl', 'wb') as fp:
                pickle.dump(carros, fp)
        if not Carrinho.objects.filter(atual='atual').exists():
          return render (request,'home.html',{'mensagem':'É necessário estar logado em um pedido para gerenciar o pedido'})
     
     carro=Carrinho.objects.get(atual='atual')
     with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
     with open('preco.pkl', 'rb') as fp: 
            precos = pickle.load(fp)
     
     total=0
     lista=[]
     for pratos in carros.keys():
             if pratos in precos.keys():
                lista.append(pratos)
                price=int(precos[pratos])
                total+=carros[pratos]*price
     return render (request,'home.html',{'mensagem3': f'{carro}','mensagem2': 'coca adicionado ao pedido','preco':total,'lista':lista,'carro':carros})
     
# def ir(request):
#      if not Carrinho.objects.filter(atual='atual').exists():
#           return render (request,'home.html',{'mensagem':'É necessário estar logado em um pedido para gerenciar o pedido'})
     
#      carro=Carrinho.objects.get(atual='atual')
#      with open(f'{carro}.pkl', 'rb') as fp: 
#             carros = pickle.load(fp)
#      with open('preco.pkl', 'rb') as fp: 
#             precos = pickle.load(fp)
     
#      total=0
#      lista=[]
#      for pratos in carros.keys():
#              if pratos in precos.keys():
#                 lista.append(pratos)
#                 price=int(precos[pratos])
#                 total+=carros[pratos]*price
     
     
#      return render (request,'pedidos.html',{'preco':total,'lista':lista,'carro':carros}) 

def retirar(request,pratos):
     carro=Carrinho.objects.get(atual='atual')
     with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
     carros.pop(pratos)
     with open(f'{carro}.pkl', 'wb') as fp: 
            carros = pickle.dump(carros,fp)

     
     with open(f'{carro}.pkl', 'rb') as fp: 
            carros = pickle.load(fp)
     with open('preco.pkl', 'rb') as fp: 
            precos = pickle.load(fp)
     
     total=0
     lista=[]
     for pratos in carros.keys():
             if pratos in precos.keys():
                lista.append(pratos)
                price=int(precos[pratos])
                total+=carros[pratos]*price
     
     
     return render (request,'home.html',{'preco':total,'lista':lista,'carro':carros})

restaurante/restaurante/casa/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <head>
    <title>Restaurante do Zé</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width = device-width, initial-scale=1">
    
    <link rel="stylesheet" href="{% static 'meusite.css' %}">
    
    
    
  </head>
  <body>
    <div id="header">
      <img class="icone-setas" src="{%static 'ham.jpg'%}" style="float: left; height:168px;">
      <img class="icone-setas" src="{%static 'hot.jpg'%}" style="float: right; height:168px;">
      <p style="color:black;font-size:150%;">Bem vindo ao restaurante do Zé.Faça sua reserva ou monte seu pedido. Não se preocupe,seu pedido fica armazenado.Você pode sair e voltar mais tarde. </p>
      
      <form action="{% url 'registrar' %}" method="POST">{% csrf_token %}
        <label style="color:black;font-size:200%">Nome do pedido:</label>
        <input type="text" name="usuario" required>
        <input  type="submit" name="res" value="salvar">
        <span >{{mensagem}}</span>
      </form>
      
      
      <a style="color:black;font-size:150%" href="#" class="botao-principal"><a style="color:black;font-size:150%;float: right;" href="{% url 'sair' %}">Sair do pedido</a></span></a>
      <a style="color:black;font-size:150%" href="{% url 'deletar' %}">Cancelar seu pedido</a>
    </div>
    
    <div id="left">
      <br>
      <br>
      
        <br>
        <p style="color:blue;">Faça sua reserva</p>
        <form action="{% url 'reserva' %}" method="POST">{% csrf_token %}
          <label>Seu nome</label>
          <input type="text" name="nome" required>
          <br>
          <label>Horario</label>
          <select name="horario" class="form-select" required>
            <option value="MN">Manhã</option>
            <option value="TR">Tarde</option>
            <option value="NO">Noite</option>
          </select>
          <br>
          <label>Local</label>
          <select name="local" class="form-select" required>
            <option value="PR">Perifeira</option>
            <option value="CN">Centro</option>
            </select>
            <br>
            <label>Dia</label>
            <input type="number" name="dia" required>
            <br>
            <input  type="submit" name="reservar" value="reservar">
            <br>
            <input  type="submit" name="cancelar" value="cancelar">
        </form>
        <p>{{mensagem}}</p>
        {% if reservas %}
          
            <p>Sua reserva foi feita para {{reservas.nome}}, dia {{reservas.data_reserva}}, no local {{reservas.get_locais_display}}, no periodo da {{reservas.get_horarios_display}}</p>
            
        {% endif %}
        <br>
        <h1 style="color:blue;">Aqui está o pedido {{mensagem3}} e o total a pagar</h1>
    <!-- <a href="{% url 'voltar' %}">Voltar ao menu</a> -->
    <p style="color:blue;">O total do pedido é: {{preco}}</p>
    {% if lista %}
    {% for prato,num in carro.items %}
    <p>{{prato}}--quantidade:{{num}}<span><a href="{% url 'retirar' pratos=prato %}"><img src="{%static 'cancel.png'%}" class="media-object  img-responsive img-thumbnail" style="width:20; height:20px;"></a></span></p>
    <!-- <a href="{% url 'retirar' pratos=prato %}"><img src="{%static 'cancel.png'%}" class="media-object  img-responsive img-thumbnail" style="float: left;width:30; height:30px;"></a> -->
    {% endfor %}
    {% endif %}
        
        </div>
    <div id="right">
      <h1>Pratos principais</h1>
      <p>{{mensagem2}}</p>
      <p>escolha quais dos pratos principais gostaria de por no pedido</p>
      <img class="icone-setas" src="{%static 'ham2.jpg'%}">
      <p>Hamburguer  Preço: 20</p>
      <a href="{% url 'ham' %}">Adicionar ao pedido</a>
      <br>
      <br>
      <img class="icone-setas" src="{%static 'fritas.jpg'%}">
      <p>Fritas  Preço: 15</p>
      
      <a href="{% url 'fritas' %}">Adicionar ao pedido</a>
      <br>
      <br>
      <img class="icone-setas" src="{%static 'coca.jpg'%}">
      <p>Coca  Preço: 10</p>
      <a href="{% url 'coca' %}">Adicionar ao pedido</a>
      <h2>Adicionar um prato ao cardapio</h2>
      <form action="{% url 'adicionar_prato' %}" method="POST">{% csrf_token %}
        <label>nome do prato</label>
        <input type="text" name="nome_prato" required>
        <br>
        <label>preco do prato</label>
        
        <input type="number" name="preco_prato" required>
        <br>
        <input  type="submit" name="add" value="adicionar prato ao cardápio">
      </form>
      <p>{{prato}}</p>
      <h2>Veja nossos outros pratos: <span><a href="{% url 'menu' %}">Menu</a></span></h2>
      <p>{{vazio}}</p>
        {% if menu %}
        {% for pratos, pre in menu.items %}
        {% if pratos != 'hamburguer' and pratos != 'fritas' and  pratos != 'coca'%}
        <p>{{pratos}} Preço: {{pre}}</p>
        <a href="{% url 'prato_pedido' prato=pratos %}">Adicionar ao pedido</a>
        <a href="{% url 'retirar_prato' prato=pratos %}">Retirar prato do cardapio</a>
        {% endif %}
        {% endfor %}
        {% endif %}
        
      </div>
      
      <div id="footer">
        <P style="color:blue;font-size:150%;">Contato: restaurante@email.com (12) 9999-9999</P>
      </div>
    
  </body>
</html>